# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170314_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
